### PR TITLE
fix underscore method for single letter words

### PR DESCRIPTION
**Pull request by az7arul**
This deals with #86

### CODE REVIEW

**Comment by jprichardson** [comment]
Looks good to me.

**Comment by az7arul** [comment]
@jprichardson whats the build process ? should I just merge this ?

**Comment by jprichardson** [comment]
Change process:

1. Submit PR for significant changes (wait for acknowledgement), minor changes like bugfixes it's ok to commit directly yourself.
2. Adhere to semver. Best explanation I've found of semver http://semver-ftw.org/
3. You can use `tin` to alter versions for all package files https://github.com/jprichardson/tin.
4. Make sure to update `CHANGELOG.md`.
5. Run `make min`. (We should move to gulp)
6. Commit the new version number with commit message being the version number. Should contain only the version number changes in package files, changelog changes, and new min file.
7. Create a tag with with the version number. Tag message should be the changelog changes.
8. Push and npm publish. Btw, what is your npm username?

**Comment by az7arul** [comment]
az7arul

**Comment by jprichardson** [comment]
Done.

**Comment by az7arul** [comment]
Published to npm :)

**Comment by jprichardson** [comment]
:+1: Awesome, thanks!

**Pull request merged**
