### PR TITLE
Changed the single quote html representation from &apos; to &#39

### PR DESCRIPTION
**Pull request by geekuillaume**
Fixing #92

### CODE REVIEW

**Comment by az7arul** [comment]
+1

**Comment by verespej** [comment]
@jprichardson Any chance of merging this? The fix would be appreciated. The change is simple and identical to fix for underscore.

**Comment by jprichardson** [comment]
Sure @verespej this is a breaking change. Also, I'd like help with a maintainer.

**Comment by verespej** [comment]
@jprichardson Thanks for the quick response. Good point about the breaking change. Merging isn't urgent as it's easy enough to work around, so no pressure, though it'd be nice to have.

I haven't been a contributor to any significant OSS projects. I'm a little trepidatious about committing due to time constrains and just came across this project due to the referenced issue, which manifested as a bug in a dependent OSS project I'm using.

What are your specific expectations?

**Pull request closed without merging**
