### PR TITLE
use gulp to build

### PR DESCRIPTION
**Pull request by az7arul**
@jprichardson I think this needs a good look.

* moved to gulp for building it
* uses browserify [#134](https://github.com/jprichardson/string.js/issues/134)
* changes `main` to dist/* from lib/*

You might want to make sure bower/component/npm works with this and the test/browser.test.html is ok.

### CODE REVIEW

**Comment by jprichardson** [comment]
I like this a lot! Before we merge, what do you think about removing bower (AMD) and component support? People could use Webpack/Browserify to add bower (AMD) support back. We could even create another repo called `string-amd` or `string-bower` for something like that. But build tools are sophisticated enough these days that libraries should be able to build using one module format and then provide interfaces for the rest through the build process. It would simplify our lives some. Thoughts?

**Comment by az7arul** [comment]
I think by default it should support both. We could work on something like `lodash-cli` to give user ability to get custom builds or use that to push code to repo's  like string-amd. We should look at how the `lodash` folks are doing things before making a decision.

**Comment by jprichardson** [comment]
I agree that using `lodash` as an ideal model and I'm in favor of that. This PR looks good as far as I can tell.

**Comment by az7arul** [comment]
Can you take a look at the test/browser.test.html ? seems to be its broken
because of this not sure though.

**Comment by jprichardson** [comment]
My guess without looking at it ATM is that it's because count was extracted
out into its own file. It needs to be put back in string.js until we refine
our build process.

On Mon, Mar 23, 2015 at 2:55 PM, Azharul Islam <notifications@github.com>
wrote:

> Can you take a look at the test/browser.test.html ? seems to be its broken
> because of this not sure though.
>
> On Tue, Mar 24, 2015 at 1:51 AM, JP Richardson <notifications@github.com>
> wrote:
>
> > I agree that using lodash as an ideal model and I'm in favor of that.
> > This PR looks good as far as I can tell.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/jprichardson/string.js/pull/135#issuecomment-85166910>
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jprichardson/string.js/pull/135#issuecomment-85167868>
> .
>



-- 
Simple & Secure Bitcoin Wallet: https://www.coinbolt.com
Bitcoin / JavaScript: http://cryptocoinjs.com
Follow JP Richardson on Twitter: https://twitter.com/jprichardson

**Comment by jprichardson** [comment]
We don't have to do this now, but we should ultimately drop
browser.test.html in favor of using mochify/saucelabs.

On Mon, Mar 23, 2015 at 3:36 PM, JP Richardson <jprichardson@gmail.com>
wrote:

> My guess without looking at it ATM is that it's because count was
> extracted out into its own file. It needs to be put back in string.js until
> we refine our build process.
>
> On Mon, Mar 23, 2015 at 2:55 PM, Azharul Islam <notifications@github.com>
> wrote:
>
>> Can you take a look at the test/browser.test.html ? seems to be its broken
>> because of this not sure though.
>>
>> On Tue, Mar 24, 2015 at 1:51 AM, JP Richardson <notifications@github.com>
>> wrote:
>>
>> > I agree that using lodash as an ideal model and I'm in favor of that.
>> > This PR looks good as far as I can tell.
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <
>> https://github.com/jprichardson/string.js/pull/135#issuecomment-85166910>
>>
>> > .
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jprichardson/string.js/pull/135#issuecomment-85167868>
>> .
>>
>
>
>
> --
> Simple & Secure Bitcoin Wallet: https://www.coinbolt.com
> Bitcoin / JavaScript: http://cryptocoinjs.com
> Follow JP Richardson on Twitter: https://twitter.com/jprichardson
>
>


-- 
Simple & Secure Bitcoin Wallet: https://www.coinbolt.com
Bitcoin / JavaScript: http://cryptocoinjs.com
Follow JP Richardson on Twitter: https://twitter.com/jprichardson

**Comment by az7arul** [comment]
extracting count is not a problem here since browserify takes care of that
problem, in firefox the count tests passed but the style was broken.

**Comment by az7arul** [comment]
will merge it after I address the Travis CI build failure

**Comment by az7arul** [comment]
@jprichardson  This needs some more work.
1. Fix the build system for node 0.8
2. Fix the `extendPrototype` method since it returns an object instead of string
```js
'hi'.capitalize()
[String: 'Hi']
```
3. Change spec for `restorePrototype()` since `endsWith` is specified in (ECMA6)[http://people.mozilla.org/~jorendorff/es6-draft.html#sec-string.prototype.endswith] and `iojs` and some browser have it as a built in method.

**Comment by jprichardson** [comment]
1. Let's drop Node 0.8 and just stick with 0.10, 0.12, iojs.
2. Fix it how?
3. Sounds good to me.

**Comment by jprichardson** [comment]
I dropped `0.8`: https://github.com/jprichardson/string.js/commit/82da0e7e272813df7196aef07b558daa2c80a53d

**Comment by az7arul** [comment]
`extendPrototype` is still broken, probably it was broken before this change. I will look into it today.

**Comment by az7arul** [comment]
glad this is finally over

**Comment by jprichardson** [comment]
Awesome, nice work!

**Pull request merged**
