### PR TITLE
add sauce-ci

### PR DESCRIPTION
**Pull request by az7arul**

### CODE REVIEW

**Comment by az7arul** [comment]
@jprichardson https://saucelabs.com/browser-matrix/stringjs.svg

**Comment by az7arul** [comment]
`gulp test` now runs both `gulp unit-test` ( run with mocha ) and `gulp browser-test` ( run with mochify using opensauce). All the major browsers are added.

**Comment by az7arul** [comment]
merging this without releasing a new version since this only effects build process.

**Comment by jprichardson** [comment]
Looks good!

**Pull request merged**
